/* 
 Design a system for XYZ Bank for storing account details, 
Every account will have type either saving account or current account 
For every account interest rate and minimum balance need to be stored.
Interest rate for saving account is 4% and for current account 1%
Minimum balance for saving account will be 20000 and current account will be 1000
For each account store account holder details(fname, lname, mobile, email) 
id will be autogenerated 3 letters of fname, 3letters of lname, count of account.
 
If it’s a saving account, then store chequebooknumber
If current account then store number of transactions/day.
*/
#include<iostream>
#include "SavingAcc.h"
#include "CurrentAcc.h"

using namespace std;

int main(){

	Account a1;
	char fname1[10]="Harry";
	char lname1[10]="Potter";
	char mobile1[10]="456889";
	char email1[25]="harrypotter@hogwarts";
	Account *a2 = new CurrentAcc(fname1, lname1, mobile1, email1);
	a2->display();
	
	
	char fname2[10]="Peter";
	char lname2[10]="Parker";
	char mobile2[10]="458339";
	char email2[20]="peterparker@nyc";
	char cbn2[20]="233545656788";
	Account *a3 = new SavingAcc(fname2, lname2, mobile2, email2, cbn2);
	a3->display();
	delete a2; delete a3;

  /*
	Account *a3 = new SavingAcc("Peter","Parker","458339","peterparker@nyc", "233545656788");
	a3->display();
	delete a1;
	delete a2;
	return 0;
	*/
	
	//Employee ob(10,"Rajan","Hr","mgr");
//	Account *a1= new Account("Lodu","Lalit","4251101","lodu@gmail");
//	a1->display();

	return 0;
}

/*
Employee ob(10,"Rajan","Hr","mgr");
  ob.display();
  Employee* emp=new Employee(11,"Revati","design","UXDesigner");
  ob.display();
  emp->display();
  
  SalariedEmp semp(10,"Rajan","Hr","mgr",2345);
  semp.display();
  
  SalariedEmp *semp1=new SalariedEmp(10,"Atharva","admin","CEO",55555);
  semp1->display();
  
 Employee* emp1=new SalariedEmp(11,"Ajay","admin","CEO",55555);
  emp1->display();
*/
